//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonMCEAddin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmazonMCEAddin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ac3_icon {
            get {
                object obj = ResourceManager.GetObject("ac3-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f5b0a28b415e443810130a4bcb86e50d800508cc.
        /// </summary>
        internal static string AndroidSignatureHexKey {
            get {
                return ResourceManager.GetString("AndroidSignatureHexKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {AD8F02DC-0137-423F-81FC-68D77ABD9CB8}.
        /// </summary>
        internal static string AppId {
            get {
                return ResourceManager.GetString("AppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Application {
            get {
                object obj = ResourceManager.GetObject("Application", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://webservices.amazon.com/AWSECommerceService/2011-08-01.
        /// </summary>
        internal static string AWSNameSpace {
            get {
                return ResourceManager.GetString("AWSNameSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Button {
            get {
                object obj = ResourceManager.GetObject("Button", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_gray {
            get {
                object obj = ResourceManager.GetObject("button-gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_highlighted {
            get {
                object obj = ResourceManager.GetObject("button-highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CategoryBox {
            get {
                object obj = ResourceManager.GetObject("CategoryBox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CategoryGallery {
            get {
                object obj = ResourceManager.GetObject("CategoryGallery", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ChildTitle {
            get {
                object obj = ResourceManager.GetObject("ChildTitle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to garethbarr.com.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Controls {
            get {
                object obj = ResourceManager.GetObject("Controls", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mceamazoncookies.dat.
        /// </summary>
        internal static string CookieFileName {
            get {
                return ResourceManager.GetString("CookieFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 132000000001.
        /// </summary>
        internal static string DeviceID {
            get {
                return ResourceManager.GetString("DeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A2W5AJPLW5Q6YM.
        /// </summary>
        internal static string DeviceTypeID {
            get {
                return ResourceManager.GetString("DeviceTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Selected.
        /// </summary>
        internal static string DialogCaption {
            get {
                return ResourceManager.GetString("DialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {AD8F02DC-0137-423F-81FC-68D77ABD9CB9}.
        /// </summary>
        internal static string EntryPointId {
            get {
                return ResourceManager.GetString("EntryPointId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fmw:15-app:1.1.19.
        /// </summary>
        internal static string Firmware {
            get {
                return ResourceManager.GetString("Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/AIV/ps3/v1.2.1-1mtsp/assets/home/empty-library.png.
        /// </summary>
        internal static string Home_Your_Watchlist {
            get {
                return ResourceManager.GetString("Home_Your_Watchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imgaiv {
            get {
                object obj = ResourceManager.GetObject("imgaiv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Login {
            get {
                object obj = ResourceManager.GetObject("Login", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Menu {
            get {
                object obj = ResourceManager.GetObject("Menu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MenuItem {
            get {
                object obj = ResourceManager.GetObject("MenuItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string MinimumSearchTextLength {
            get {
                return ResourceManager.GetString("MinimumSearchTextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/movies_genres_drama.jpg.
        /// </summary>
        internal static string Movie_Genres_Drama {
            get {
                return ResourceManager.GetString("Movie_Genres_Drama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/movies_genres_horror.jpg.
        /// </summary>
        internal static string Movie_Genres_Horror {
            get {
                return ResourceManager.GetString("Movie_Genres_Horror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/movies_genres_international.jpg.
        /// </summary>
        internal static string Movie_Genres_International {
            get {
                return ResourceManager.GetString("Movie_Genres_International", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/movies_genres_kids.jpg.
        /// </summary>
        internal static string Movie_Genres_Kids_And_Family {
            get {
                return ResourceManager.GetString("Movie_Genres_Kids_And_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/movies_genres_romance.jpg.
        /// </summary>
        internal static string Movie_Genres_Romance {
            get {
                return ResourceManager.GetString("Movie_Genres_Romance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/movies_genres_scifi.jpg.
        /// </summary>
        internal static string Movie_Genres_SciFi_And_Fantasy {
            get {
                return ResourceManager.GetString("Movie_Genres_SciFi_And_Fantasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/movies_genres.jpg.
        /// </summary>
        internal static string Movies_All_Genres {
            get {
                return ResourceManager.GetString("Movies_All_Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/movies_genres_drama.jpg.
        /// </summary>
        internal static string Movies_All_Genres_Drama {
            get {
                return ResourceManager.GetString("Movies_All_Genres_Drama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/movies_genres_horror.jpg.
        /// </summary>
        internal static string Movies_All_Genres_Horror {
            get {
                return ResourceManager.GetString("Movies_All_Genres_Horror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/movies_genres_international.jpg.
        /// </summary>
        internal static string Movies_All_Genres_International {
            get {
                return ResourceManager.GetString("Movies_All_Genres_International", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/movies_genres_kids.jpg.
        /// </summary>
        internal static string Movies_All_Genres_Kids_And_Family {
            get {
                return ResourceManager.GetString("Movies_All_Genres_Kids_And_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/movies_genres_scifi.jpg.
        /// </summary>
        internal static string Movies_All_Genres_SciFi_And_Fantasy {
            get {
                return ResourceManager.GetString("Movies_All_Genres_SciFi_And_Fantasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/movies_editorspicks.jpg.
        /// </summary>
        internal static string Movies_Editors_Picks {
            get {
                return ResourceManager.GetString("Movies_Editors_Picks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/movies_editorspicks_page_to_screen.jpg.
        /// </summary>
        internal static string Movies_Editors_Picks_From_Page_to_Screen {
            get {
                return ResourceManager.GetString("Movies_Editors_Picks_From_Page_to_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/movies_editorspicks_history.jpg.
        /// </summary>
        internal static string Movies_Editors_Picks_History_Repeats_Itself {
            get {
                return ResourceManager.GetString("Movies_Editors_Picks_History_Repeats_Itself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/movies_genres_kids.jpg.
        /// </summary>
        internal static string Movies_For_The_Kids {
            get {
                return ResourceManager.GetString("Movies_For_The_Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/movies_popular.jpg.
        /// </summary>
        internal static string Movies_Popular_Movies {
            get {
                return ResourceManager.GetString("Movies_Popular_Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play_gray {
            get {
                object obj = ResourceManager.GetObject("play-gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play_highlighted {
            get {
                object obj = ResourceManager.GetObject("play-highlighted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap prime_button_panel {
            get {
                object obj = ResourceManager.GetObject("prime-button-panel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/movies_genres.jpg.
        /// </summary>
        internal static string Prime_Instant_Video_Movie_Genres {
            get {
                return ResourceManager.GetString("Prime_Instant_Video_Movie_Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/movies_top_prime.jpg.
        /// </summary>
        internal static string Prime_Instant_Video_Popular_Movies {
            get {
                return ResourceManager.GetString("Prime_Instant_Video_Popular_Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/prime_popular.jpg.
        /// </summary>
        internal static string Prime_Instant_Video_Popular_TV_Shows {
            get {
                return ResourceManager.GetString("Prime_Instant_Video_Popular_TV_Shows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/tv_genres.jpg.
        /// </summary>
        internal static string Prime_Instant_Video_TV_Genres {
            get {
                return ResourceManager.GetString("Prime_Instant_Video_TV_Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string PrimeOnly {
            get {
                return ResourceManager.GetString("PrimeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rated_g {
            get {
                object obj = ResourceManager.GetObject("rated_g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rated_nc17 {
            get {
                object obj = ResourceManager.GetObject("rated_nc17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rated_nr {
            get {
                object obj = ResourceManager.GetObject("rated_nr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rated_pg {
            get {
                object obj = ResourceManager.GetObject("rated_pg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rated_pg13 {
            get {
                object obj = ResourceManager.GetObject("rated_pg13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rated_r {
            get {
                object obj = ResourceManager.GetObject("rated_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SearchBox {
            get {
                object obj = ResourceManager.GetObject("SearchBox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SeasonDetails {
            get {
                object obj = ResourceManager.GetObject("SeasonDetails", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SimpleEditBox {
            get {
                object obj = ResourceManager.GetObject("SimpleEditBox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spinner {
            get {
                object obj = ResourceManager.GetObject("spinner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stars_full {
            get {
                object obj = ResourceManager.GetObject("stars_full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stars_half {
            get {
                object obj = ResourceManager.GetObject("stars_half", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Styles {
            get {
                object obj = ResourceManager.GetObject("Styles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tv_14 {
            get {
                object obj = ResourceManager.GetObject("tv_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tv_g {
            get {
                object obj = ResourceManager.GetObject("tv_g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/tv_genres_action.jpg.
        /// </summary>
        internal static string TV_Genres_Action_And_Adventure {
            get {
                return ResourceManager.GetString("TV_Genres_Action_And_Adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/tv_genres_animation.jpg.
        /// </summary>
        internal static string TV_Genres_Animation {
            get {
                return ResourceManager.GetString("TV_Genres_Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/tv_genres_comedy.jpg.
        /// </summary>
        internal static string TV_Genres_Comedy {
            get {
                return ResourceManager.GetString("TV_Genres_Comedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/tv_genres_drama.jpg.
        /// </summary>
        internal static string TV_Genres_Drama {
            get {
                return ResourceManager.GetString("TV_Genres_Drama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/tv_genres_kids.jpg.
        /// </summary>
        internal static string TV_Genres_Kids_And_Family {
            get {
                return ResourceManager.GetString("TV_Genres_Kids_And_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/tv_genres_scifi.jpg.
        /// </summary>
        internal static string TV_Genres_SciFi_And_Fantasy {
            get {
                return ResourceManager.GetString("TV_Genres_SciFi_And_Fantasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tv_ma {
            get {
                object obj = ResourceManager.GetObject("tv_ma", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tv_pg {
            get {
                object obj = ResourceManager.GetObject("tv_pg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/tv_genres.jpg.
        /// </summary>
        internal static string TV_Shows_All_Genres {
            get {
                return ResourceManager.GetString("TV_Shows_All_Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/tv_genres_action.jpg.
        /// </summary>
        internal static string TV_Shows_All_Genres_Action_And_Adventure {
            get {
                return ResourceManager.GetString("TV_Shows_All_Genres_Action_And_Adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/tv_genres_animation.jpg.
        /// </summary>
        internal static string TV_Shows_All_Genres_Animation {
            get {
                return ResourceManager.GetString("TV_Shows_All_Genres_Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/tv_genres_comedy.jpg.
        /// </summary>
        internal static string TV_Shows_All_Genres_Comedy {
            get {
                return ResourceManager.GetString("TV_Shows_All_Genres_Comedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/tv_genres_drama.jpg.
        /// </summary>
        internal static string TV_Shows_All_Genres_Drama {
            get {
                return ResourceManager.GetString("TV_Shows_All_Genres_Drama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/tv_genres_kids.jpg.
        /// </summary>
        internal static string TV_Shows_All_Genres_Kids_And_Family {
            get {
                return ResourceManager.GetString("TV_Shows_All_Genres_Kids_And_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/tv_genres_scifi.jpg.
        /// </summary>
        internal static string TV_Shows_All_Genres_SciFi_And_Fantasy {
            get {
                return ResourceManager.GetString("TV_Shows_All_Genres_SciFi_And_Fantasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/tv_editorspicks.jpg.
        /// </summary>
        internal static string TV_Shows_Editors_Picks {
            get {
                return ResourceManager.GetString("TV_Shows_Editors_Picks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/tv_editorspicks_british_invasion.jpg.
        /// </summary>
        internal static string TV_Shows_Editors_Picks_British_Invasion {
            get {
                return ResourceManager.GetString("TV_Shows_Editors_Picks_British_Invasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/tv_genres_kids.jpg.
        /// </summary>
        internal static string TV_Shows_For_The_Kids {
            get {
                return ResourceManager.GetString("TV_Shows_For_The_Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ec2.images-amazon.com/images/G/01/digital/video/ps3/tv_popular.jpg.
        /// </summary>
        internal static string TV_Shows_Popular_TV_Shows {
            get {
                return ResourceManager.GetString("TV_Shows_Popular_TV_Shows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/prime_tvchannels.jpg.
        /// </summary>
        internal static string TV_Shows_TV_Channels {
            get {
                return ResourceManager.GetString("TV_Shows_TV_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/tv_tvchannels_abc.jpg.
        /// </summary>
        internal static string TV_Shows_TV_Channels_ABC {
            get {
                return ResourceManager.GetString("TV_Shows_TV_Channels_ABC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/tv_tvchannels_amc.jpg.
        /// </summary>
        internal static string TV_Shows_TV_Channels_AMC {
            get {
                return ResourceManager.GetString("TV_Shows_TV_Channels_AMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/tv_tvchannels_bbc.jpg.
        /// </summary>
        internal static string TV_Shows_TV_Channels_BBC {
            get {
                return ResourceManager.GetString("TV_Shows_TV_Channels_BBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/tv_tvchannels_cbs.jpg.
        /// </summary>
        internal static string TV_Shows_TV_Channels_CBS {
            get {
                return ResourceManager.GetString("TV_Shows_TV_Channels_CBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/tv_tvchannels_comedy_central.jpg.
        /// </summary>
        internal static string TV_Shows_TV_Channels_Comedy_Central {
            get {
                return ResourceManager.GetString("TV_Shows_TV_Channels_Comedy_Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/tv_tvchannels_discovery.jpg.
        /// </summary>
        internal static string TV_Shows_TV_Channels_Discovery {
            get {
                return ResourceManager.GetString("TV_Shows_TV_Channels_Discovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/tv_tvchannels_fox.jpg.
        /// </summary>
        internal static string TV_Shows_TV_Channels_Fox {
            get {
                return ResourceManager.GetString("TV_Shows_TV_Channels_Fox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/tv_tvchannels_hbo.jpg.
        /// </summary>
        internal static string TV_Shows_TV_Channels_HBO {
            get {
                return ResourceManager.GetString("TV_Shows_TV_Channels_HBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/tv_tvchannels_mtv.jpg.
        /// </summary>
        internal static string TV_Shows_TV_Channels_MTV {
            get {
                return ResourceManager.GetString("TV_Shows_TV_Channels_MTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/tv_tvchannels_nbc.jpg.
        /// </summary>
        internal static string TV_Shows_TV_Channels_NBC {
            get {
                return ResourceManager.GetString("TV_Shows_TV_Channels_NBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/tv_tvchannels_nickelodeon.jpg.
        /// </summary>
        internal static string TV_Shows_TV_Channels_Nickelodeon {
            get {
                return ResourceManager.GetString("TV_Shows_TV_Channels_Nickelodeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/tv_tvchannels_pbs.jpg.
        /// </summary>
        internal static string TV_Shows_TV_Channels_PBS {
            get {
                return ResourceManager.GetString("TV_Shows_TV_Channels_PBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/tv_tvchannels_showtime.jpg.
        /// </summary>
        internal static string TV_Shows_TV_Channels_Showtime {
            get {
                return ResourceManager.GetString("TV_Shows_TV_Channels_Showtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/tv_tvchannels_starz.jpg.
        /// </summary>
        internal static string TV_Shows_TV_Channels_Starz {
            get {
                return ResourceManager.GetString("TV_Shows_TV_Channels_Starz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/tv_tvchannels_travel.jpg.
        /// </summary>
        internal static string TV_Shows_TV_Channels_Travel_Channel {
            get {
                return ResourceManager.GetString("TV_Shows_TV_Channels_Travel_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/tv_tvchannels_nickelodeon.jpg.
        /// </summary>
        internal static string TV_Shows_TV_Channels_Travel_Channel_Nickelodeon_Nick_Jr {
            get {
                return ResourceManager.GetString("TV_Shows_TV_Channels_Travel_Channel_Nickelodeon_Nick_Jr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://g-ecx.images-amazon.com/images/G/01/digital/video/ps3/tv_tvchannels_usa.jpg.
        /// </summary>
        internal static string TV_Shows_TV_Channels_USA_Network {
            get {
                return ResourceManager.GetString("TV_Shows_TV_Channels_USA_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tv_y {
            get {
                object obj = ResourceManager.GetObject("tv_y", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tv_y7 {
            get {
                object obj = ResourceManager.GetObject("tv_y7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tv_y7fv {
            get {
                object obj = ResourceManager.GetObject("tv_y7fv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unrated {
            get {
                object obj = ResourceManager.GetObject("unrated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VideoDetails {
            get {
                object obj = ResourceManager.GetObject("VideoDetails", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VideoGallery {
            get {
                object obj = ResourceManager.GetObject("VideoGallery", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VideoRating {
            get {
                object obj = ResourceManager.GetObject("VideoRating", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VideoTitle {
            get {
                object obj = ResourceManager.GetObject("VideoTitle", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
